# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Theme
theme: "ocean"
day_night: true
font: ""
font_size: "M"

# Basic Info
site_type: "Person"
local_business_type: ""
org_name: ""
description: ""

# Site Features
highlight: true
highlight_languages: 
  - "r"
math: false
diagram: false
privacy_pack: false

# Contact details
email: "kshankar@usm.my"
phone: "+604 653 4632"

address:
  street: "National Advanced IPv6 Centre (NAv6), Level 6, School of Computer Sciences Building, Universiti Sains Malaysia"
  city: "USM"
  region: "Penang"
  postcode: "11800"
  country: "Malaysia"
  country_code: "MY"

coordinates:
  latitude: "5.354623"
  longitude: "100.301446"

directions: "Take the lift to the 6th floor and turn right at the entrance to head over to NAv6."

appointment_url: "https://calendly.com/kshankar_usm"

contact_links:
  - icon: "twitter"
    icon_pack: "fab"
    name: "DM Me"
    link: "https://twitter.com/sh_nk_r"

  - icon: "skype"
    icon_pack: "fab"
    name: "Skype Me"
    link: "skype:shankar.karuppayah?call"

  - icon: "telegram"
    icon_pack: "fab"
    name: "Telegram Me"
    link: "https://telegram.me/@skusm"

# Social
sharing_image: "avatar.jpg"
twitter: "sh_nk_r"

# Regional Settings
date_format: "Jan 2, 2006"
time_format: "3:04 PM"
address_format: "de"

# Advanced
main_menu:
  align: "l"
  show_logo: true

reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
link_authors: true
abstract_length: 135

avatar:
  gravatar: false
  shape: "circle"

address_formats:
  en-us:
    order:
      - "street"
      - "city"
      - "region"
      - "postcode"
    delimiters:
      - ", "
      - ", "
      - " "
      - ""

  en-gb:
    order:
      - "street"
      - "city"
      - "region"
      - "postcode"
    delimiters:
      - ", "
      - ", "
      - ", "
      - ""

  de:
    order:
      - "street"
      - "postcode"
      - "city"
    delimiters:
      - "<br>"
      - " "
      - ""
